### ISSUE TITLE
hey man SpamText can't change!!!

### ISSUE THREAD

**Issue by yj94** [Coopyy/EgguWare-Unturned#1]
the SpamText can't change. change it and in the game will be the same "egguware lol" it no work. and may i ask if the cheat will update? i love it could u continue to make it better？？ very thank for u。if u can could u give u Skype numb to me？？i want to chat with u！！！

**Comment by Coopyy** [comment]
seems fine for me. are you sure you're changing the right text field?

i also have no plans to continue development for this project

**Comment by yj94** [comment]
Thank you for your reply. I know the cause of the problem. It will store the text resource in the computer and load it, but I modified "Spam text" to display normally on other computers. Thank you very much for your reply. If you can continue to strengthen this project, I will be very happy. After all, it is very practical.Text field change complete.Love u dude.
