### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by tensorov** [Coopyy/EgguWare-Unturned#2]
Error	CS1061	'ItemGunAsset' does not contain a definition for 'bladeID' and no accessible extension method 'bladeID' accepting a first argument of type 'ItemGunAsset' could be found (are you missing a using directive or an assembly reference?)	EgguWare	C:\Users\User\Desktop\EgguWare-Unturned-master\Cheat\Overrides\hkUsableGun.cs	143	Active

(File wasn't edited)

**Comment by Coopyy** [comment]
duplicate answer in https://github.com/Coopyy/EgguWare-Unturned/issues/3
