### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by tensorov** [Coopyy/EgguWare-Unturned#3]
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'usage' of 'PlayerInput.sendRaycast(RaycastInfo, ERaycastInfoUsage)'	EgguWare	C:\Users\User\Desktop\EgguWare-Unturned-master\Cheat\Overrides\hkUsableGun.cs	82	Active
_______________________________________________________________________________________________________________________________________
Error	CS7036	There is no argument given that corresponds to the required formal parameter 'usage' of 'PlayerInput.sendRaycast(RaycastInfo, ERaycastInfoUsage)'	EgguWare	C:\Users\User\Desktop\EgguWare-Unturned-master\Cheat\Overrides\hkUsableGun.cs	61	Active
#Files weren't edited

**Comment by Coopyy** [comment]
i dont have any issues downloading the source and compiling it without any changes.
did you change references to the newest files? something in the game may have changed, requiring the cheat to be updated

Edit: i tried with the newest game file, i get the same errors. as for the errors i suggest updating the cheats version of the `CalcHitMarker()` function with the games, and also adding `ERaycastInfoUsage.Gun` to the second parameter of the function to look like this: `Player.player.input.sendRaycast(ri, ERaycastInfoUsage.Gun)`
