### ISSUE TITLE
I have tried to update this and i have fixed all errors but i have this error "Texture2D does not contain definition for EncodeToJPG"

### ISSUE THREAD

**Issue by WildCD** [Coopyy/EgguWare-Unturned#6]
Am i missing an reference?

**Comment by WildCD** [comment]
I am having more of these same errors. I might have some weird reference or i am missing something.

**Comment by Coopyy** [comment]
this will probably need some updates as youre referencing new unturned & updated unity files

**Comment by bossotron13** [comment]
ye

**Comment by bossotron13** [comment]
Un close
