### ISSUE TITLE
I can't use this cheat with Battleyes.

### ISSUE THREAD

**Issue by piwawa** [Coopyy/EgguWare-Unturned#7]
Is it necessary that launch game without BattlEye Anti-Cheat?

**Comment by bossotron13** [comment]
Yeah, if you don't and you haven't implemented a bypass then you will get battleye banned.

**Comment by Coopyy** [comment]
thank you for your words of wisdom @bossotron13 🙏

**Comment by piwawa** [comment]
> Yeah, if you don't and you haven't implemented a bypass then you will get battleye banned.

Honestly, I don't care about being banned. I just want to use this mod online with BattlEye. My real question is how to make it work with BattlEye?
