### ISSUE TITLE
Not drawing cursor

### ISSUE THREAD

**Issue by hiddenFSBuser** [Coopyy/EgguWare-Unturned#8]
Cursor is not drawing in cheat, i try to do method GUI.DrawTexture(new Rect(SDG.Framework.UI.Sleek2.Sleek2Pointer.cursor.width-16/2, SDG.Framework.UI.Sleek2.Sleek2Pointer.cursor.height-16/2, 16, 16), SDG.Framework.UI.Sleek2.Sleek2Pointer.cursor);, and method Cursor.SetCursor() (with argumets), but its not worked, how to add cursor visibility in egguware cheat in menu?

**Comment by Coopyy** [comment]
try using your own texture, GUI.DrawTexture should work fine

**Comment by merlepx** [comment]
late response but set the texture in [main.cs](https://github.com/Coopyy/EgguWare-Unturned/blob/master/Cheat/Menu/Main.cs#L77) to `UI/Glazier_IMGUI/Cursor` and it should show the cursor

**Comment by Coopyy** [comment]
^
